In [1]:
import numpy as np

In [9]:
#a. Using Numpy, write a basic array of operations on single array to add x to each element of array and subtract y from each element of array. 
a=np.array([1,2,3,4,5,6,7])
np.add(a,7)
np.subtract(a,6)

array([-5, -4, -3, -2, -1,  0,  1])

In [13]:
#b. Using Numpy, write a program to add, subtract and multiply two matrices. 
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[8,9,2],[5,6,7],[3,4,5]])
print("ADD")
np.add(m1,m2)

ADD
SUB
MATMUL


array([[ 27,  33,  31],
       [ 75,  90,  73],
       [123, 147, 115]])

In [14]:
print("SUB")
np.subtract(m1,m2)


SUB


array([[-7, -7,  1],
       [-1, -1, -1],
       [ 4,  4,  4]])

In [15]:
print("MATMUL")
np.matmul(m1,m2)

MATMUL


array([[ 27,  33,  31],
       [ 75,  90,  73],
       [123, 147, 115]])

In [16]:
#. Write a Python program to do the following operations: Library: NumPy

In [20]:
#i)	Create multi-dimensional arrays and find its shape and dimension 
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[5,6,7],[9,5,2],[2,3,4]]])
a.shape

(2, 3, 3)

In [22]:
#ii)	Create a matrix full of zeros and ones 
z=np.zeros((4,5))
z


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
o=np.ones((5,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#iii)	Reshape and flatten data in the array 
a=a.reshape(3,3,2)
a

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 5],
        [6, 7]],

       [[9, 5],
        [2, 2],
        [3, 4]]])

In [42]:
a=a.flatten()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6, 7, 9, 5, 2, 2, 3, 4])

In [37]:
#iv)	Append data vertically and horizontally 
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[7,8],[5,6],[8,9]])
np.hstack((a1,a2))

array([[1, 2, 3, 7, 8],
       [4, 5, 6, 5, 6],
       [7, 8, 9, 8, 9]])

In [39]:
b2=[[1,2,3],[4,5,6]]
np.vstack((a1,b2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
#v)	Apply indexing and slicing on array 

In [44]:
#vi)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 
print('min',np.min(a))
print('max',np.max(a))
print('mean',np.mean(a))
print('median',np.median(a))
print('std',np.std(a))


min 1
max 9
mean 4.888888888888889
median 5.0
std 2.401131420552701


In [47]:
#vii)	Dot and matrix product of two arrays 
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[34,5,6],[7,8,9],[2,3,4]])
np.dot(mat1,mat2)

array([[ 54,  30,  36],
       [183,  78,  93],
       [312, 126, 150]])

In [48]:
print("matrix product")
mat1*mat2

matrix product


array([[34, 10, 18],
       [28, 40, 54],
       [14, 24, 36]])

In [50]:
#viii)	Compute the Eigen values of a matrix 
w,v=np.linalg.eig(mat1)
print("eigen values",w)

eigen values [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [61]:
#ix)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 
cmat1=np.array([[3,1],[1,2]])
cmat2=np.array([9,8])
v=np.linalg.solve(cmat1,cmat2)
print(v)

[2. 3.]


In [54]:
#x)	Compute the multiplicative inverse of a matrix 
np.linalg.inv(mat1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [57]:
#xi)	Compute the rank of a matrix 
np.linalg.matrix_rank(mat1)

2

In [55]:
#Compute the determinant of an array
np.linalg.det(mat1)

-9.51619735392994e-16